### ISSUE TITLE
More than one Event Contract

### ISSUE THREAD

**Issue by johnmurphy01** [digitalcreations/Pusher.NET#3]
I want to set up more than one event contract with the same data structure. The event names that broadcast contain the same data structure in some instances.

```cs
PusherClient.AddContract(EventContract.Create<FileData>("file:update"));
PusherClient.AddContract(EventContract.Create<FileData>("file:delete"));
```

I have subscribed to the `channel.GetEventSubscription<FileData>().EventEmitted` event but whenever I cause my client to pick up either of these events, all I get back is:

```
pusher_internal:subscription_succeeded
{"presence":null}
```

If I remove one of the Event Contracts, things work as expected.

How do I add more than one Event Contract?

Thanks

**Comment by vegardlarsen** [comment]
@johnmurphy01 Thanks for reporting this. I can't find an immediate cause for this by a casual browse through the source. Could you perhaps create a minimal reproducible solution and send it to me?

**Comment by johnmurphy01** [comment]
Turns out it was my Data Structure. I had a double that was not nullable and so it was complaining. It's probably safe to close this "bug".

**Comment by vegardlarsen** [comment]
Good to know. :)
